name: Ubuntu Build on master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install deps
      run: apt install libglfw3-dev libglew-dev mesa-common-dev libglm-dev
    - name: make
      run: make all
    - uses: actions/upload-artifact@v2
      with:
        name: gek.app
        path: gek.app
